# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89ff36143ad2d08936c69835bbf5badf3f8c8b46b25e94b7408cb8572d144d494456fa8f0b7bf51a6411bf07e57dbff2dea157301d62428ea8f7bddb068dc951

test:
  secret_key_base: c9d86731b455e8c397eaae94b1d5a972270100ede613824b3d05fdfbc310a9f9960a07fa82e2cd50c90ecae413d67db6c4367033c52b22bbc262690f739ea624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
